name: RewardsPlugin
version: 1.1.0
main: net.serashard.rewardsplugin.RewardsPlugin
author: SeraShard
api-version: '1.21.11'

commands:
  resetrewards:
    description: Changes whether a player has received join rewards yet
    usage: /<command>
    permission-message: "You do not have permission to use this command"
    permission: rewardsplugin.resetrewards

permissions:
  rewardsplugin.resetrewards:
    default: op
